In [ ]:
!pip install gym

In [54]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [55]:
env = gym.make('FrozenLake-v0')

In [56]:
acion_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,acion_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Q Learning Algorithm:
* Step 1: Start from the starting state for each new episode in the loop.
* Step 2: Set the exploration rate threhold randomly between 0 to 1.
* Step 3: If the threshold value > exploration rate then eploit the data, else explore.
* Step 4: Update the Q table.
* Step 5: Update Exploration Rate.
* Step 6: Update the state to new state.
* Step 7: Cal the reward for the current state.
* Step 8: Repeat step 1 to 7 for N number of episodes.

# Exploration And Exploitation:
It is used for determining whether to explore or to eploit the information gain from the exploration. 1st the exploration rate is set to 1 and epsilon i.e. eploration rate threshold which is selected randomly between 0 and 1 and if the epsilon > exploration rate then the exploitation is performed else eploration is done.

# Q-Function:
* Action Value Function:
  \begin{eqnarray*} q_{\pi }\left( s,a\right) &=&E_{\pi }\left[ G_{t}\mid S_{t}=s,A_{t}=a \rule[-0.05in]{0in}{0.2in}\right] \\ &=&E_{\pi }\left[ \sum_{k=0}^{\infty }\gamma ^{k}R_{t+k+1}\mid S_{t}=s,A_{t}=a\right] \text{.} \end{eqnarray*}

* State Value Function:
\begin{eqnarray*} v_{\pi }\left( s\right) &=&E_{\pi}\left[
                                                \rule[-0.05in]{0in}{0.2in}G_{t}\mid S_{t}=s\right] \\ &=&E_{\pi }\left[ \sum_{k=0}^{\infty }\gamma ^{k}R_{t+k+1}\mid S_{t}=s\right] \text{.} \end{eqnarray*}

* Here gamma value denotes the dicount rate.
* After each episode the exploration decays.



In [76]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.01

reward_all_episodes=[]

# Q-learning Algo
for episode in range(num_episodes):
    state = env.reset()
    rewards_current_episode = 0

    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()

        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]) - q_table[state, action])
        

        state = new_state
        rewards_current_episode += reward
        if done: break

    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
    reward_all_episodes.append(rewards_current_episode)

# Cal and print the reward per 1000 rounds
rewards_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count=1000

print("AVERAGE")
for r in rewards_per_thousand_episodes:
  print(count,":",str(sum(r/1000)))
  count+=1000

print("Q-Table")
print(q_table)


AVERAGE
1000 : 0.5030000000000003
2000 : 0.6810000000000005
3000 : 0.6720000000000005
4000 : 0.6550000000000005
5000 : 0.6790000000000005
6000 : 0.6940000000000005
7000 : 0.7100000000000005
8000 : 0.6520000000000005
9000 : 0.6600000000000005
10000 : 0.7000000000000005
Q-Table
[[0.49928852 0.47352678 0.47099726 0.47359682]
 [0.27616284 0.31310282 0.30970402 0.40467693]
 [0.35299893 0.27288119 0.27512663 0.28895406]
 [0.00760728 0.16167901 0.06886011 0.05937051]
 [0.5212925  0.32339043 0.38123739 0.41720369]
 [0.         0.         0.         0.        ]
 [0.31752935 0.10593243 0.14491849 0.10605798]
 [0.         0.         0.         0.        ]
 [0.35843278 0.40412746 0.4812062  0.56876155]
 [0.52819476 0.61984626 0.44777148 0.41601555]
 [0.60404711 0.44390203 0.32085985 0.32504734]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.38436464 0.50456909 0.72571972 0.58000908]
 [0.69060102 0.87984644 0.73295972 0.75644582]
 [0.         0.   

In [81]:
for episode in range(3):
  state=env.reset()
  done=False
  print("Episode", episode+1)
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action=np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)


    if done:
     clear_output(wait=True)
     env.render()
     if reward==1:
       print("You reached the goal")
       time.sleep(3)      
     else:
      print("You fell in the hole")
      time.sleep(3)
     clear_output(wait=True)
     break
     
    state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
You reached the goal
