In [1]:
!pip install gym

In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [5]:
env = gym.make('FrozenLake-v0')

In [7]:
acion_space_size=env.action_space.n
state_space_size=env.observation_space.n

q_table=np.zeros((state_space_size,acion_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
exploration_decay_rate=0.001

# Q Learning Algorithm:
* Step 1: Start from the starting state for each new episode in the loop.
* Step 2: Set the exploration rate threhold randomly between 0 to 1.
* Step 3: If the threshold value > exploration rate then eploit the data, else explore.
* Step 4: Update the Q table.
* Step 5: Update Exploration Rate.
* Step 6: Update the state to new state.
* Step 7: Cal the reward for the current state.
* Step 8: Repeat step 1 to 7 for N number of episodes.

# Exploration And Exploitation:
It is used for determining whether to explore or to eploit the information gain from the exploration. 1st the exploration rate is set to 1 and epsilon i.e. eploration rate threshold which is selected randomly between 0 and 1 and if the epsilon > exploration rate then the exploitation is performed else eploration is done.

# Q-Function:
* Action Value Function:
  \begin{eqnarray*} q_{\pi }\left( s,a\right) &=&E_{\pi }\left[ G_{t}\mid S_{t}=s,A_{t}=a \rule[-0.05in]{0in}{0.2in}\right] \\ &=&E_{\pi }\left[ \sum_{k=0}^{\infty }\gamma ^{k}R_{t+k+1}\mid S_{t}=s,A_{t}=a\right] \text{.} \end{eqnarray*}

* State Value Function:
\begin{eqnarray*} v_{\pi }\left( s\right) &=&E_{\pi}\left[
                                                \rule[-0.05in]{0in}{0.2in}G_{t}\mid S_{t}=s\right] \\ &=&E_{\pi }\left[ \sum_{k=0}^{\infty }\gamma ^{k}R_{t+k+1}\mid S_{t}=s\right] \text{.} \end{eqnarray*}

* Here gamma value denotes the dicount rate.
* After each episode the exploration decays.



In [27]:
reward_all_episodes=[]

# Q-learning Algo
for episode in range(num_episodes):
  state=env.reset()
  
  done=False
  rewards_current_episode=0
  for steps in range(max_steps_per_episode):

    #Exploration-Exploitation Trade-Off
    exploration_rate_threshold = random.uniform(0, 1)
    if exploration_rate_threshold > exploration_rate:
        action = np.argmax(q_table[state,:]) 
    else:
        action = env.action_space.sample()
      
    new_state, reward, done, info = env.step(action)

    # Update Q-Table
    q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
    learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))

    state = new_state
    rewards_current_episode+=reward

    if done==True:
      break
    
  # Exploration rate decay
  exploration_rate = min_exploration_rate + \
    (max_exploration_rate - min_exploration_rate) * np.exp(-max_exploration_rate*episode)

  reward_all_episodes.append(rewards_current_episode)

# Cal and print the reward per 1000 rounds
rewards_per_thousand_episodes = np.split(np.array(reward_all_episodes),num_episodes/1000)
count=1000

print("AVERAGE")
for r in rewards_per_thousand_episodes:
  print(count,":",str(sum(r/1000)))
  count+=1000

print("Q-Table")
print(q_table)


AVERAGE
1000 : 0.6560000000000005
2000 : 0.6630000000000005
3000 : 0.6700000000000005
4000 : 0.6570000000000005
5000 : 0.6930000000000005
6000 : 0.6840000000000005
7000 : 0.6580000000000005
8000 : 0.6790000000000005
9000 : 0.6620000000000005
10000 : 0.6590000000000005
Q-Table
[[0.57963188 0.4771334  0.49038846 0.48804845]
 [0.22495918 0.18200858 0.19301685 0.47773254]
 [0.3325047  0.23784946 0.23238586 0.23964138]
 [0.05627423 0.         0.         0.        ]
 [0.61141183 0.44746712 0.28698367 0.35600107]
 [0.         0.         0.         0.        ]
 [0.2204046  0.12594695 0.12890787 0.09725564]
 [0.         0.         0.         0.        ]
 [0.40533845 0.40030661 0.35843433 0.64263667]
 [0.44142429 0.66956398 0.27251087 0.37697208]
 [0.62610389 0.29431128 0.37065792 0.27536528]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.28802673 0.36430952 0.73798783 0.48583438]
 [0.72893219 0.89707131 0.75862475 0.72473532]
 [0.         0.   

In [31]:
for episode in range(3):
  state=env.reset()
  done=False
  print("Episode", episode+1)
  time.sleep(1)

  for step in range(max_steps_per_episode):
    clear_output(wait=True)
    env.render()
    time.sleep(0.3)

    action=np.argmax(q_table[state,:])
    new_state, reward, done, info = env.step(action)


    if done:
     clear_output(wait=True)
     env.render()
     if reward==1:
       print("You reached the goal")
       time.sleep(3)      
     else:
      print("You fell in the hole")
      time.sleep(3)
     clear_output(wait=True)
     break
     
    state = new_state

env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG
You fell in the hole
